eureka:
  client:
    healthcheck:
      enabled: true

owms:
  commands:
    tms:
      to:
        routing-key: to.*
        exchange-name: tms.commands
        queue-name: tms.to.commands
  events:
    common:
      tu:
        exchange-name: common.tu
